# YAML dump of robot model 'm2', 20210831_06:26
# created with Phobos 1.0.1 "Capricious Choutengan" - https://github.com/dfki-ric/phobos

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 #Hz

steering_lb:
  type: effort_controllers/JointPositionController
  joint: steering_strut_lb_to_drive_motor_lb
  pid: {p: 1.0, i: 0.0, d: 0.0}
steering_lf_ctrlr:
  type: effort_controllers/JointPositionController
  joint: steering_strut_lf_to_drive_motor_lf
  pid: {p: 1.0, i: 0.0, d: 0.0}
steering_rb:
  type: effort_controllers/JointPositionController
  joint: steering_strut_rb_to_drive_motor_rb
  pid: {p: 1.0, i: 0.0, d: 0.0}
steering_rf_ctrlr:
  type: effort_controllers/JointPositionController
  joint: steering_strut_rf_to_drive_motor_rf
  pid: {p: 1.0, i: 0.0, d: 0.0}

wheel_lb_ctrlr:
  type: effort_controllers/JointVelocityController
  joint: drive_motor_lb_to_wheel_lb
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 10.0}
wheel_lf_ctrlr:
  type: effort_controllers/JointVelocityController
  joint: drive_motor_lf_to_wheel_lf
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 10.0}
wheel_rb_ctrlr:
  type: effort_controllers/JointVelocityController
  joint: drive_motor_rb_to_wheel_rb
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 10.0}
wheel_rf_ctrlr:
  type: effort_controllers/JointVelocityController
  joint: drive_motor_rf_to_wheel_rf
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 10.0}
