// Generated by gencpp from file umrr_driver/sens_param_reqRequest.msg
// DO NOT EDIT!


#ifndef UMRR_DRIVER_MESSAGE_SENS_PARAM_REQREQUEST_H
#define UMRR_DRIVER_MESSAGE_SENS_PARAM_REQREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace umrr_driver
{
template <class ContainerAllocator>
struct sens_param_reqRequest_
{
  typedef sens_param_reqRequest_<ContainerAllocator> Type;

  sens_param_reqRequest_()
    : section(0)
    , param(0)  {
    }
  sens_param_reqRequest_(const ContainerAllocator& _alloc)
    : section(0)
    , param(0)  {
  (void)_alloc;
    }



   typedef int32_t _section_type;
  _section_type section;

   typedef int32_t _param_type;
  _param_type param;





  typedef boost::shared_ptr< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sens_param_reqRequest_

typedef ::umrr_driver::sens_param_reqRequest_<std::allocator<void> > sens_param_reqRequest;

typedef boost::shared_ptr< ::umrr_driver::sens_param_reqRequest > sens_param_reqRequestPtr;
typedef boost::shared_ptr< ::umrr_driver::sens_param_reqRequest const> sens_param_reqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator1> & lhs, const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator2> & rhs)
{
  return lhs.section == rhs.section &&
    lhs.param == rhs.param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator1> & lhs, const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace umrr_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee7fb720fa0b0247c82d71fa3ef07771";
  }

  static const char* value(const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee7fb720fa0b0247ULL;
  static const uint64_t static_value2 = 0xc82d71fa3ef07771ULL;
};

template<class ContainerAllocator>
struct DataType< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "umrr_driver/sens_param_reqRequest";
  }

  static const char* value(const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 section\n"
"int32 param\n"
;
  }

  static const char* value(const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.section);
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sens_param_reqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::umrr_driver::sens_param_reqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::umrr_driver::sens_param_reqRequest_<ContainerAllocator>& v)
  {
    s << indent << "section: ";
    Printer<int32_t>::stream(s, indent + "  ", v.section);
    s << indent << "param: ";
    Printer<int32_t>::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UMRR_DRIVER_MESSAGE_SENS_PARAM_REQREQUEST_H
