// Generated by gencpp from file umrr_driver/sens_status.msg
// DO NOT EDIT!


#ifndef UMRR_DRIVER_MESSAGE_SENS_STATUS_H
#define UMRR_DRIVER_MESSAGE_SENS_STATUS_H

#include <ros/service_traits.h>


#include <umrr_driver/sens_statusRequest.h>
#include <umrr_driver/sens_statusResponse.h>


namespace umrr_driver
{

struct sens_status
{

typedef sens_statusRequest Request;
typedef sens_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sens_status
} // namespace umrr_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::umrr_driver::sens_status > {
  static const char* value()
  {
    return "93c8fafc2bd33a52659a315b24e02f5f";
  }

  static const char* value(const ::umrr_driver::sens_status&) { return value(); }
};

template<>
struct DataType< ::umrr_driver::sens_status > {
  static const char* value()
  {
    return "umrr_driver/sens_status";
  }

  static const char* value(const ::umrr_driver::sens_status&) { return value(); }
};


// service_traits::MD5Sum< ::umrr_driver::sens_statusRequest> should match
// service_traits::MD5Sum< ::umrr_driver::sens_status >
template<>
struct MD5Sum< ::umrr_driver::sens_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_status >::value();
  }
  static const char* value(const ::umrr_driver::sens_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_statusRequest> should match
// service_traits::DataType< ::umrr_driver::sens_status >
template<>
struct DataType< ::umrr_driver::sens_statusRequest>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_status >::value();
  }
  static const char* value(const ::umrr_driver::sens_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::umrr_driver::sens_statusResponse> should match
// service_traits::MD5Sum< ::umrr_driver::sens_status >
template<>
struct MD5Sum< ::umrr_driver::sens_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_status >::value();
  }
  static const char* value(const ::umrr_driver::sens_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_statusResponse> should match
// service_traits::DataType< ::umrr_driver::sens_status >
template<>
struct DataType< ::umrr_driver::sens_statusResponse>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_status >::value();
  }
  static const char* value(const ::umrr_driver::sens_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UMRR_DRIVER_MESSAGE_SENS_STATUS_H
