// Generated by gencpp from file umrr_driver/sens_param_req.msg
// DO NOT EDIT!


#ifndef UMRR_DRIVER_MESSAGE_SENS_PARAM_REQ_H
#define UMRR_DRIVER_MESSAGE_SENS_PARAM_REQ_H

#include <ros/service_traits.h>


#include <umrr_driver/sens_param_reqRequest.h>
#include <umrr_driver/sens_param_reqResponse.h>


namespace umrr_driver
{

struct sens_param_req
{

typedef sens_param_reqRequest Request;
typedef sens_param_reqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sens_param_req
} // namespace umrr_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::umrr_driver::sens_param_req > {
  static const char* value()
  {
    return "9a0eeee29694f2ca329fbb723ef7be91";
  }

  static const char* value(const ::umrr_driver::sens_param_req&) { return value(); }
};

template<>
struct DataType< ::umrr_driver::sens_param_req > {
  static const char* value()
  {
    return "umrr_driver/sens_param_req";
  }

  static const char* value(const ::umrr_driver::sens_param_req&) { return value(); }
};


// service_traits::MD5Sum< ::umrr_driver::sens_param_reqRequest> should match
// service_traits::MD5Sum< ::umrr_driver::sens_param_req >
template<>
struct MD5Sum< ::umrr_driver::sens_param_reqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_param_req >::value();
  }
  static const char* value(const ::umrr_driver::sens_param_reqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_param_reqRequest> should match
// service_traits::DataType< ::umrr_driver::sens_param_req >
template<>
struct DataType< ::umrr_driver::sens_param_reqRequest>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_param_req >::value();
  }
  static const char* value(const ::umrr_driver::sens_param_reqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::umrr_driver::sens_param_reqResponse> should match
// service_traits::MD5Sum< ::umrr_driver::sens_param_req >
template<>
struct MD5Sum< ::umrr_driver::sens_param_reqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_param_req >::value();
  }
  static const char* value(const ::umrr_driver::sens_param_reqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_param_reqResponse> should match
// service_traits::DataType< ::umrr_driver::sens_param_req >
template<>
struct DataType< ::umrr_driver::sens_param_reqResponse>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_param_req >::value();
  }
  static const char* value(const ::umrr_driver::sens_param_reqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UMRR_DRIVER_MESSAGE_SENS_PARAM_REQ_H
