// Generated by gencpp from file umrr_driver/sens_param.msg
// DO NOT EDIT!


#ifndef UMRR_DRIVER_MESSAGE_SENS_PARAM_H
#define UMRR_DRIVER_MESSAGE_SENS_PARAM_H

#include <ros/service_traits.h>


#include <umrr_driver/sens_paramRequest.h>
#include <umrr_driver/sens_paramResponse.h>


namespace umrr_driver
{

struct sens_param
{

typedef sens_paramRequest Request;
typedef sens_paramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sens_param
} // namespace umrr_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::umrr_driver::sens_param > {
  static const char* value()
  {
    return "d082684b67b68ff067addfa1087d79e3";
  }

  static const char* value(const ::umrr_driver::sens_param&) { return value(); }
};

template<>
struct DataType< ::umrr_driver::sens_param > {
  static const char* value()
  {
    return "umrr_driver/sens_param";
  }

  static const char* value(const ::umrr_driver::sens_param&) { return value(); }
};


// service_traits::MD5Sum< ::umrr_driver::sens_paramRequest> should match
// service_traits::MD5Sum< ::umrr_driver::sens_param >
template<>
struct MD5Sum< ::umrr_driver::sens_paramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_param >::value();
  }
  static const char* value(const ::umrr_driver::sens_paramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_paramRequest> should match
// service_traits::DataType< ::umrr_driver::sens_param >
template<>
struct DataType< ::umrr_driver::sens_paramRequest>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_param >::value();
  }
  static const char* value(const ::umrr_driver::sens_paramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::umrr_driver::sens_paramResponse> should match
// service_traits::MD5Sum< ::umrr_driver::sens_param >
template<>
struct MD5Sum< ::umrr_driver::sens_paramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::umrr_driver::sens_param >::value();
  }
  static const char* value(const ::umrr_driver::sens_paramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::umrr_driver::sens_paramResponse> should match
// service_traits::DataType< ::umrr_driver::sens_param >
template<>
struct DataType< ::umrr_driver::sens_paramResponse>
{
  static const char* value()
  {
    return DataType< ::umrr_driver::sens_param >::value();
  }
  static const char* value(const ::umrr_driver::sens_paramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UMRR_DRIVER_MESSAGE_SENS_PARAM_H
