// Generated by gencpp from file umrr_driver/sens_statusRequest.msg
// DO NOT EDIT!


#ifndef UMRR_DRIVER_MESSAGE_SENS_STATUSREQUEST_H
#define UMRR_DRIVER_MESSAGE_SENS_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace umrr_driver
{
template <class ContainerAllocator>
struct sens_statusRequest_
{
  typedef sens_statusRequest_<ContainerAllocator> Type;

  sens_statusRequest_()
    : section(0)
    , param(0)
    , type()  {
    }
  sens_statusRequest_(const ContainerAllocator& _alloc)
    : section(0)
    , param(0)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _section_type;
  _section_type section;

   typedef int32_t _param_type;
  _param_type param;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::umrr_driver::sens_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::umrr_driver::sens_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sens_statusRequest_

typedef ::umrr_driver::sens_statusRequest_<std::allocator<void> > sens_statusRequest;

typedef boost::shared_ptr< ::umrr_driver::sens_statusRequest > sens_statusRequestPtr;
typedef boost::shared_ptr< ::umrr_driver::sens_statusRequest const> sens_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::umrr_driver::sens_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::umrr_driver::sens_statusRequest_<ContainerAllocator1> & lhs, const ::umrr_driver::sens_statusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.section == rhs.section &&
    lhs.param == rhs.param &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::umrr_driver::sens_statusRequest_<ContainerAllocator1> & lhs, const ::umrr_driver::sens_statusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace umrr_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::umrr_driver::sens_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::umrr_driver::sens_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::umrr_driver::sens_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e7b73d2c3ad243160428ecc93cd4758";
  }

  static const char* value(const ::umrr_driver::sens_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e7b73d2c3ad2431ULL;
  static const uint64_t static_value2 = 0x60428ecc93cd4758ULL;
};

template<class ContainerAllocator>
struct DataType< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "umrr_driver/sens_statusRequest";
  }

  static const char* value(const ::umrr_driver::sens_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 section\n"
"int32 param\n"
"string type\n"
;
  }

  static const char* value(const ::umrr_driver::sens_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.section);
      stream.next(m.param);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sens_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::umrr_driver::sens_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::umrr_driver::sens_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "section: ";
    Printer<int32_t>::stream(s, indent + "  ", v.section);
    s << indent << "param: ";
    Printer<int32_t>::stream(s, indent + "  ", v.param);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UMRR_DRIVER_MESSAGE_SENS_STATUSREQUEST_H
